[package]
name = "com-croftsoft-lib-animation"
version = "0.0.3-SNAPSHOT"
authors = ["David Wallace Croft <david@CroftSoft.com>"]
categories = ["game-development", "graphics", "gui", "rendering", "visualization"]
description = "CroftSoft Library for Animation"
edition = "2021"
homepage = "https://www.CroftSoft.com/"
keywords = ["game-development", "graphics", "gui", "rendering", "visualization"]
license = "MIT"
publish = false
readme = "README.md"
repository = "https://github.com/david-wallace-croft/com-croftsoft-lib-animation"

[dependencies]
com-croftsoft-lib-role = "0.1.4"
